version: '3.8'

services:
  source_service:
    build:
      context: ./source_service
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/log_aggregator
    networks:
      - lognet

  collector_service:
    build:
      context: ./collector_service
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/log_aggregator
    networks:
      - lognet

  monitoring_service:
    build:
      context: ./monitoring_service
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/log_aggregator
    networks:
      - lognet

  search_service:
    build:
      context: ./search_service
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/log_aggregator
    ports:
      - "5000:5000"
    networks:
      - lognet

  retention_scheduler_service:
    build:
      context: ./retention_scheduler_service
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/log_aggregator
    networks:
      - lognet

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lognet

networks:
  lognet:

volumes:
  mongo_data: